name: omle
version: 0.1.0.0
github: "senysenyseny16/omle"
license: BSD-3-Clause
author: "Arsenii Ianchenko"
maintainer: "arseny@protonmail.com"
copyright: "2025 Arsenii"

extra-source-files:
- README.md

description: YAML linter/formatter

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  omle-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omle

tests:
  omle-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omle
    - hspec
